version: '3.3'
services:
  db:
    container_name: api-gateway-db
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: 'isi-db'
      MYSQL_USER: 'isiadmin'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3307'
    volumes:
      - my-db:/var/lib/mysql
  app:
    depends_on:
      - db
    container_name: api-gateway
    build: ./
    restart: on-failure
    ports:
      - 8080:8080
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  my-db: